config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets

  get 'search/show'
  get 'search/results'

  get 'admin/welcome/index'
  root 'admin/welcome#index'

  resources :trains

  namespace :admin do

    resources :trains do
      resources :cars, shallow: true
    end

    resources :railway_stations do
      patch :update_number, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train
  before_create :set_number
  validates :number, uniqueness: { scope: :train_id }

  private

  def set_number
    self.number = train.cars.count + 1
  end
end

app/models/coupe_car.rb
class CoupeCar < Car
  validates :top_places, :bottom_places, presence: true
end

app/models/down_car.rb
class DownCar < Car
  validates :bottom_places, presence: true
end

app/models/economy_car.rb
class EconomyCar < Car
  validates :top_places, :bottom_places, :top_side_places, :bottom_side_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :routes_railway_stations
  has_many :routes, through: :routes_railway_stations

  validates :title, presence: true, uniqueness: true

  scope :ordered, -> { joins(:routes_railway_stations).order('routes_railway_stations.railway_stations_number').uniq }

  def update_number(route, number)
    route_station = route_station(route)
    route_station.update(railway_station_number: number) if route_station
  end

  def number_in(route)
    route_station(route).try(:railway_station_number)
  end

  protected

  def route_station(route)
    @route_station ||= routes_railway_stations.where(route: route).first
  end
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :routes_railway_stations
  has_many :railway_stations, through: :routes_railway_stations
  validates :name, presence: true, uniqueness: true
end

app/models/routes_railway_station.rb
class RoutesRailwayStation < ApplicationRecord
  belongs_to :route
  belongs_to :railway_station

  default_scope -> { order(:railway_station_number) }
end

app/models/search.rb
class Search < ApplicationRecord
  def self.search(first_station_id, last_station_id)
    first_station_routes = RailwayStation.find(first_station_id.to_i).routes
    last_station_routes = RailwayStation.find(last_station_id.to_i).routes

    routes = first_station_routes & last_station_routes

    trains = []
    routes.each do |route|
      trains += route.trains
    end
    trains
  end
end

app/models/seat_car.rb
class SeatCar < Car
  validates :seat_places, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train, optional: true

  after_create :send_buy_notice
  after_destroy :send_cancel_notice

  def first_station
    RailwayStation.find(first_station_id)
  end

  def last_station
    RailwayStation.find(last_station_id)
  end

  def send_buy_notice
    TicketsMailer.buy_ticket(user, self).deliver_now
  end

  def send_cancel_notice
    TicketsMailer.cancel_ticket(user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true
  belongs_to :route
  has_many :tickets
  has_many :cars
  validates :number, presence: true, uniqueness: true

  def get_places(car_type, places_type)
    res = 0
    cars.where(type: car_type).each do |car|
      res += car.send(places_type)
    end

    res
  end

  def cars_sort=(order)
    super(true) if order == :from_head
    super(false) if order == :from_tail
  end

  def cars_sort
    return :from_head if super

    :from_tail
  end

  def sort
    if cars_sort == :from_head
      cars.order('number ASC')
    else
      cars.order('number DESC')
    end
  end

  def first_station
    route.railway_stations.first
  end

  def last_station
    route.railway_stations.last
  end

  def departure_in
    route.railway_stations.first.departure_time if route.railway_stations.first
  end

  def arrival_in
    route.railway_stations.last.arrival_time if route.railway_stations.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable
  has_many :tickets
  validates :name, presence: true
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def edit; end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route], notice: 'Route was successfully created.'
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path, notice: 'Route was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_url, notice: 'Route was successfully destroyed.'
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

  def results
    @trains = Search.search(search_params[:first_station_id],
                            search_params[:last_station_id])

    @first_station_id = search_params[:first_station_id]
    @last_station_id = search_params[:last_station_id]
  end

  private

  def search_params
    params.require(:search).permit(:first_station_id, :last_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_ticket, only: %i[show edit destroy]

  def index
    @tickets = Ticket.where(user_id: current_user.id)
  end

  def show
    @train = @ticket.train
  end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.train = Train.find(ticket_params[:train_id])
    @ticket.first_station_id = ticket_params[:first_station_id]
    @ticket.last_station_id = ticket_params[:last_station_id]

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully purchased.'
    else
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to search_show_path, notice: 'Ticket was successfully canceled.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:first_station_id,
                                   :last_station_id,
                                   :train_id,
                                   :full_name,
                                   :passport,
                                   :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/routes/_attr_list.html.erb
<% @route.railway_stations.each do |station| %>
  <tr>
    <td> <%= link_to station.title, [:admin, station] %> </td>
    <td>
      <%= form_tag update_number_admin_railway_station_path(station), method: :patch do %>
        <%= number_field_tag :number, station.number_in(@route)%>
        <%= hidden_field_tag :route_id, @route.id %>
        <%= submit_tag 'Change' %>
      <% end %>

    </td>
  </tr>  
<% end %>

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: {style: "display: #{hidden ? 'none' : 'block'}"} do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
     <h2><%= t('common.errors')%> </h2>

      <ul>
        <% route.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit', action: route.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/routes/_stations_list.html.erb
<% @route.railway_stations.each do |station| %>
  <tr class="table-secondary">
    <td> <%= link_to station.title, [:admin, station] %> </td>
    <td>
      <%= form_tag update_number_admin_railway_station_path(station), method: :patch do %>
        <%= number_field_tag :number, station.number_in(@route)%>
        <%= hidden_field_tag :route_id, @route.id %>
        <%= submit_tag 'Change' %>
      <% end %>
    </td>
  </tr>  
<% end %>

app/views/admin/routes/_trains_list.html.erb
<table border = "1" rules="all">
  <thead>
    <tr class="table-primary">
      <th>Number</th>
      <th colspan="3">Actions</th>
      <th>Departure</th>
      <th>Arrival</th>
    </tr>
  </thead>

  <tbody>
    <% @route.trains.each do |train| %>
      <tr class="table-secondary">
        <td><%= train.number %></td>
        <td><%= link_to 'Show', admin_train_path(train) %></td>
        <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
        <td><%= link_to 'Destroy', admin_train_path(train), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= train.departure_in %></td>
        <td><%= train.arrival_in %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

app/views/admin/routes/edit.html.erb
<h1> <%= t('.title') %> </h1>

<%= render 'form', route: @route %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table border = "1" rules="all" class="table table-hover">
  <thead>
    <tr class="table-primary">
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr class="table-secondary">
        <td>
          <%= route.name %>
          <%= render 'form', route: route, hidden: true %>
        </td>
        <td><%= link_to 'Show', admin_route_path(route) %></td>
        <td><%= link_to 'Edit', '', class: 'edit_route', data: {route_id: route.id} %></td>
        <td><%= link_to 'Destroy', admin_route_path(route), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to "New Route", new_admin_route_path, method: :get, class: 'btn btn-primary' %>

app/views/admin/routes/new.html.erb
<h1> <%= t('.title') %> </h1>

<%= render 'form', route: @route %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<% if @route.trains.empty?%>
  <strong>There are no trains on the route</strong><br>
<% else %>
  <strong>Trains on the route:</strong>
  <%= render 'trains_list' %> 
<% end %>

<br>

<% if @route.railway_stations.empty?%>
  <strong>There are no stations on the route</strong><br>
<% else %>
  <strong>Stations in the route:</strong>
  <table border = "1" rules="all">
      <thead>
        <tr>
          <th width=200px>Название</th>
          <th>Расположение</th>
        </tr>
      </thead>
      <tbody>
        <%= render 'stations_list' %>
      </tbody> 
    </table> 
<% end %>

<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>