config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets

  get 'search/show'
  get 'search/results'

  get 'admin/welcome/index'
  root 'admin/welcome#index'

  resources :trains

  namespace :admin do

    resources :trains do
      resources :cars, shallow: true
    end

    resources :railway_stations do
      patch :update_number, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train
  before_create :set_number
  validates :number, uniqueness: { scope: :train_id }

  private

  def set_number
    self.number = train.cars.count + 1
  end
end

app/models/coupe_car.rb
class CoupeCar < Car
  validates :top_places, :bottom_places, presence: true
end

app/models/down_car.rb
class DownCar < Car
  validates :bottom_places, presence: true
end

app/models/economy_car.rb
class EconomyCar < Car
  validates :top_places, :bottom_places, :top_side_places, :bottom_side_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :routes_railway_stations
  has_many :routes, through: :routes_railway_stations

  validates :title, presence: true, uniqueness: true

  scope :ordered, -> { joins(:routes_railway_stations).order('routes_railway_stations.railway_stations_number').uniq }

  def update_number(route, number)
    route_station = route_station(route)
    route_station.update(railway_station_number: number) if route_station
  end

  def number_in(route)
    route_station(route).try(:railway_station_number)
  end

  protected

  def route_station(route)
    @route_station ||= routes_railway_stations.where(route: route).first
  end
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :routes_railway_stations
  has_many :railway_stations, through: :routes_railway_stations
  validates :name, presence: true, uniqueness: true
end

app/models/routes_railway_station.rb
class RoutesRailwayStation < ApplicationRecord
  belongs_to :route
  belongs_to :railway_station

  default_scope -> { order(:railway_station_number) }
end

app/models/search.rb
class Search < ApplicationRecord
  def self.search(first_station_id, last_station_id)
    first_station_routes = RailwayStation.find(first_station_id.to_i).routes
    last_station_routes = RailwayStation.find(last_station_id.to_i).routes

    routes = first_station_routes & last_station_routes

    trains = []
    routes.each do |route|
      trains += route.trains
    end
    trains
  end
end

app/models/seat_car.rb
class SeatCar < Car
  validates :seat_places, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train, optional: true

  after_create :send_buy_notice
  after_destroy :send_cancel_notice

  def first_station
    RailwayStation.find(first_station_id)
  end

  def last_station
    RailwayStation.find(last_station_id)
  end

  def send_buy_notice
    TicketsMailer.buy_ticket(user, self).deliver_now
  end

  def send_cancel_notice
    TicketsMailer.cancel_ticket(user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true
  belongs_to :route
  has_many :tickets
  has_many :cars
  validates :number, presence: true, uniqueness: true

  def get_places(car_type, places_type)
    res = 0
    cars.where(type: car_type).each do |car|
      res += car.send(places_type)
    end

    res
  end

  def cars_sort=(order)
    super(true) if order == :from_head
    super(false) if order == :from_tail
  end

  def cars_sort
    return :from_head if super

    :from_tail
  end

  def sort
    if cars_sort == :from_head
      cars.order('number ASC')
    else
      cars.order('number DESC')
    end
  end

  def first_station
    route.railway_stations.first
  end

  def last_station
    route.railway_stations.last
  end

  def departure_in
    route.railway_stations.first.departure_time if route.railway_stations.first
  end

  def arrival_in
    route.railway_stations.last.arrival_time if route.railway_stations.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable
  has_many :tickets
  validates :name, presence: true
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::BaseController
  before_action :set_train, only: %i[new create]
  before_action :set_car, only: %i[edit update destroy show]

  def index
    @cars = Car.all
  end

  def show; end

  def new
    @car = Car.new
  end

  def edit; end

  def create
    @car = @train.cars.new(car_params)

    if @car.save
      redirect_to [:admin, @car.becomes(Car)], notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to [:admin, @car.becomes(Car)], notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to admin_cars_path, notice: 'Car was successfully destroyed.'
  end

  private

  def set_car
    @car = Car.find(params[:id]).becomes(Car)
  end

  def set_train
    @train = Train.find(params[:train_id])
  end

  def car_params
    params.require(:car).permit(:type, :top_places, :bottom_places, :top_side_places, :bottom_side_places, :train_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

  def results
    @trains = Search.search(search_params[:first_station_id],
                            search_params[:last_station_id])

    @first_station_id = search_params[:first_station_id]
    @last_station_id = search_params[:last_station_id]
  end

  private

  def search_params
    params.require(:search).permit(:first_station_id, :last_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_ticket, only: %i[show edit destroy]

  def index
    @tickets = Ticket.where(user_id: current_user.id)
  end

  def show
    @train = @ticket.train
  end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.train = Train.find(ticket_params[:train_id])
    @ticket.first_station_id = ticket_params[:first_station_id]
    @ticket.last_station_id = ticket_params[:last_station_id]

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully purchased.'
    else
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to search_show_path, notice: 'Ticket was successfully canceled.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:first_station_id,
                                   :last_station_id,
                                   :train_id,
                                   :full_name,
                                   :passport,
                                   :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/cars/_car.html.erb
<tr class="table-secondary">
  <td><%= car.type || 'No type' %></td>
  <td><%= link_to 'Show', admin_car_path(car) %></td>
  <td><%= link_to 'Edit', edit_admin_car_path(car) %></td>
  <td><%= link_to 'Destroy', admin_car_path(car), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/cars/_form.html.erb
<%= form_for [:admin, @train, @car] do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('common.errors')%> </h2>

      <ul>
        <% @car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field select_car_type">
    <%= f.label :type %>
    <%= f.select :type, 
    '<option value="CoupeCar">CoupeCar</option>
     <option value="DownCar">DownCar</option>
     <option value="EconomyCar">EconomyCar</option>'.html_safe %>
  </div>

  <div class="field places top">
    <%= f.label 'Top places' %>
    <%= f.number_field :top_places %>
  </div>

  <div class="field places bottom">
    <%= f.label 'Bottom places' %>
    <%= f.number_field :bottom_places %>
  </div>

  <div class="field  places top_side">
    <%= f.label 'Top side places' %>
    <%= f.number_field :top_side_places %>
  </div>

  <div class="field places bottom_side">
    <%= f.label 'Bottom side places' %>
    <%= f.number_field :bottom_side_places %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', admin_car_path %> |
<%= link_to 'Back', admin_cars_path %>

app/views/admin/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Car</h1>

<table border = "1" rules="all" class="table table-hover">
  <thead>
    <tr class="table-primary">
      <th>Type</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @cars %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_admin_car_path %><br>
<%= link_to 'Home', admin_welcome_index_url %>

app/views/admin/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

app/views/admin/cars/show.html.erb
<p>
  <strong>Type:</strong>
  <%= @car.type || 'No type' %>
</p>

<p>
  <strong>Bottom places:</strong>
  <%= @car.bottom_places || 0 %><br>

  <strong>Top places:</strong>
  <%= @car.top_places || 0 %><br>

  <strong>Side Bottom places:</strong>
  <%= @car.top_side_places || 0 %><br>

  <strong>Side Top places:</strong>
  <%= @car.top_side_places || 0 %>
</p>  


<%= link_to 'Edit', edit_admin_car_path(@car) %> |
<%= link_to 'Back', [:admin, @car.train] %>

app/views/cars/_car.html.erb
<tr>
  <td><%= car.type || 'No type' %></td>
  <td><%= link_to 'Show', car %></td>
  <td><%= link_to 'Edit', edit_car_path(car) %></td>
  <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/cars/_form.html.erb
<%= form_for([@train, @car]) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% @car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    <%= f.select :type, 
    '<option value="CoupeCar">Coupe</option> 
     <option value="EconomyCar">Economy</option>'.html_safe %>
  </div>

  <div class="field">
    <%= f.label 'Top places' %>
    <%= f.text_field :top_places%>
  </div>

  <div class="field">
    <%= f.label 'Lower places' %>
    <%= f.text_field :bottom_places %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p>
  <strong>Type:</strong>
  <%= @car.type || 'No type' %>
</p>

<p>
  <strong>Bottom places:</strong>
  <%= @car.bottom_places || 0 %><br>

  <strong>Top places:</strong>
  <%= @car.top_places || 0 %><br>

  <strong>Side Bottom places:</strong>
  <%= @car.top_side_places || 0 %><br>

  <strong>Side Top places:</strong>
  <%= @car.top_side_places || 0 %>
</p>  


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>