config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets

  get 'search/show'
  get 'search/results'

  get 'admin/welcome/index'
  root 'admin/welcome#index'

  resources :trains

  namespace :admin do

    resources :trains do
      resources :cars, shallow: true
    end

    resources :railway_stations do
      patch :update_number, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :routes_railway_stations
  has_many :routes, through: :routes_railway_stations

  validates :title, presence: true, uniqueness: true

  scope :ordered, -> { joins(:routes_railway_stations).order('routes_railway_stations.railway_stations_number').uniq }

  def update_number(route, number)
    route_station = route_station(route)
    route_station.update(railway_station_number: number) if route_station
  end

  def number_in(route)
    route_station(route).try(:railway_station_number)
  end

  protected

  def route_station(route)
    @route_station ||= routes_railway_stations.where(route: route).first
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: %i[show edit update destroy update_number]

  def index
    @railway_stations = RailwayStation.all
  end

  def show; end

  def new
    @railway_station = RailwayStation.new
  end

  def edit; end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to [:admin, @railway_station] , notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to admin_railway_stations_path, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to admin_railway_stations_path, notice: 'Railway station was successfully destroyed.'
  end

  def update_number
    @route = Route.find(params[:route_id])
    @railway_station.update_number(@route, params[:number])
    redirect_to [:admin, @route]
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title, route_ids: [])
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Show', railway_station %></td>
  <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table border = "1" rules="all">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %><br>
<%= link_to 'Home', welcome_index_url %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<p>
  <strong>Trains on station:</strong>
  <% @railway_station.trains.each do |train|%>
    <%= link_to "#{train.number}", train_path(train)%><br>
  <% end %>  
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>