config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tickets

  get 'search/show'
  get 'search/results'

  get 'admin/welcome/index'
  root 'admin/welcome#index'

  resources :trains

  namespace :admin do

    resources :trains do
      resources :cars, shallow: true
    end

    resources :railway_stations do
      patch :update_number, on: :member
    end

    resources :routes
    resources :tickets
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :train
  before_create :set_number
  validates :number, uniqueness: { scope: :train_id }

  private

  def set_number
    self.number = train.cars.count + 1
  end
end

app/models/coupe_car.rb
class CoupeCar < Car
  validates :top_places, :bottom_places, presence: true
end

app/models/down_car.rb
class DownCar < Car
  validates :bottom_places, presence: true
end

app/models/economy_car.rb
class EconomyCar < Car
  validates :top_places, :bottom_places, :top_side_places, :bottom_side_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :routes_railway_stations
  has_many :routes, through: :routes_railway_stations

  validates :title, presence: true, uniqueness: true

  scope :ordered, -> { joins(:routes_railway_stations).order('routes_railway_stations.railway_stations_number').uniq }

  def update_number(route, number)
    route_station = route_station(route)
    route_station.update(railway_station_number: number) if route_station
  end

  def number_in(route)
    route_station(route).try(:railway_station_number)
  end

  protected

  def route_station(route)
    @route_station ||= routes_railway_stations.where(route: route).first
  end
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :routes_railway_stations
  has_many :railway_stations, through: :routes_railway_stations
  validates :name, presence: true, uniqueness: true
end

app/models/routes_railway_station.rb
class RoutesRailwayStation < ApplicationRecord
  belongs_to :route
  belongs_to :railway_station

  default_scope -> { order(:railway_station_number) }
end

app/models/search.rb
class Search < ApplicationRecord
  def self.search(first_station_id, last_station_id)
    first_station_routes = RailwayStation.find(first_station_id.to_i).routes
    last_station_routes = RailwayStation.find(last_station_id.to_i).routes

    routes = first_station_routes & last_station_routes

    trains = []
    routes.each do |route|
      trains += route.trains
    end
    trains
  end
end

app/models/seat_car.rb
class SeatCar < Car
  validates :seat_places, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train, optional: true

  after_create :send_buy_notice
  after_destroy :send_cancel_notice

  def first_station
    RailwayStation.find(first_station_id)
  end

  def last_station
    RailwayStation.find(last_station_id)
  end

  def send_buy_notice
    TicketsMailer.buy_ticket(user, self).deliver_now
  end

  def send_cancel_notice
    TicketsMailer.cancel_ticket(user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true
  belongs_to :route
  has_many :tickets
  has_many :cars
  validates :number, presence: true, uniqueness: true

  def get_places(car_type, places_type)
    res = 0
    cars.where(type: car_type).each do |car|
      res += car.send(places_type)
    end

    res
  end

  def cars_sort=(order)
    super(true) if order == :from_head
    super(false) if order == :from_tail
  end

  def cars_sort
    return :from_head if super

    :from_tail
  end

  def sort
    if cars_sort == :from_head
      cars.order('number ASC')
    else
      cars.order('number DESC')
    end
  end

  def first_station
    route.railway_stations.first
  end

  def last_station
    route.railway_stations.last
  end

  def departure_in
    route.railway_stations.first.departure_time if route.railway_stations.first
  end

  def arrival_in
    route.railway_stations.last.arrival_time if route.railway_stations.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable
  has_many :tickets
  validates :name, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  protected 

  def check_admin
    redirect_to '/search/show' unless current_user.admin?
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show; end

  def new
    @train = Train.new
  end

  def edit; end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train], notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id, :current_station_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @stations = RailwayStation.all
  end

  def results
    @trains = Search.search(search_params[:first_station_id],
                            search_params[:last_station_id])

    @first_station_id = search_params[:first_station_id]
    @last_station_id = search_params[:last_station_id]
  end

  private

  def search_params
    params.require(:search).permit(:first_station_id, :last_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_ticket, only: %i[show edit destroy]

  def index
    @tickets = Ticket.where(user_id: current_user.id)
  end

  def show
    @train = @ticket.train
  end

  def new
    @ticket = Ticket.new
  end

  def edit; end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.train = Train.find(ticket_params[:train_id])
    @ticket.first_station_id = ticket_params[:first_station_id]
    @ticket.last_station_id = ticket_params[:last_station_id]

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully purchased.'
    else
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to search_show_path, notice: 'Ticket was successfully canceled.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:first_station_id,
                                   :last_station_id,
                                   :train_id,
                                   :full_name,
                                   :passport,
                                   :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: {style: "display: #{hidden ? 'none' : 'block'}"} do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('common.errors')%> </h2>

      <ul>
        <% train.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :current_station %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title, {}, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit t('.submit', action: train.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr class="table-secondary">
  <td>
    <%= train.number %>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to 'Show', admin_train_path(train) %></td>
  <td><%= link_to 'Edit', '', class: 'edit_train', data: {train_id: train.id} %></td>
  <td><%= link_to 'Destroy', admin_train_path(train), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <td><%= train.departure_in %></td>
  <td><%= train.arrival_in %></td>
</tr>

app/views/admin/trains/_user_train.erb
<td><%= train.number %></td>
<td><%= link_to 'Show', admin_train(train) %></td>
<td><%= train.departure_in %></td>
<td><%= train.arrival_in %></td>

app/views/admin/trains/edit.html.erb
<h1> <%= t('.title') %> </h1>

<%= render 'form', train: @train %>

<%= link_to link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table border = "1" rules="all" class="table table-hover">
  <thead>
    <tr class="table-primary">
      <th>Number</th>
      <th colspan="3">Actions</th>
      <th>Departure</th>
      <th>Arrival</th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= button_to "New Train", new_admin_train_path, method: :get, class: 'btn btn-primary' %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <% if @train.route.nil? %>
    <strong>No route assigned<strong>
  <% else %>
    <strong>Route: </strong> 
    <%= link_to "#{@train.route.name}", admin_route_path(@train.route) %>
  <% end %>
</p>

<p>
  <% if @train.current_station.nil? %>
    <strong>No current station assigned<strong>
  <% else %>
    <strong>Current_station: </strong> 
    <%= link_to "#{@train.current_station.title}", admin_railway_station_path(@train.current_station)  %>
  <% end %>
</p>

<p>
  <% if @train.cars.empty? %>
    <strong>No cars<strong>
  <% else %>
    <strong>Cars:</strong> 
    <% @train.cars.each do |c| %>
      <%= link_to c.number, admin_car_path(c) %>
    <% end %>  
  <% end %>
</p>

<p>
  <% 
    top = 0 
    lower = 0 
    @train.cars.each do |c| 
      top += c.top_places || 0
      lower += c.bottom_places || 0
    end 
  %> 

  <strong> Top places: </strong> <%= top %> <br>
  <strong> Lower places: </strong> <%= lower %>
</p>

<p>
  <%= link_to 'Add car', new_admin_train_car_path(@train) %>
</p>

<%= link_to 'Edit', edit_admin_train_path(@train) %> |
<%= link_to link_to I18n.t('common.back'), admin_trains_path %>

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
        <% train.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :current_station %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.erb
<td><%= train.number %></td>
<td><%= link_to 'Show', train %></td>
<td><%= train.departure_in %></td>
<td><%= train.arrival_in %></td>

app/views/trains/_user_train.erb
<td><%= train.number %></td>
<td><%= link_to 'Show', train %></td>
<td><%= train.departure_in %></td>
<td><%= train.arrival_in %></td>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<h1>Trains</h1>

<table border = "1" rules="all">
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3">Actions</th>
      <th>Departure</th>
      <th>Arrival</th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <% if @train.route.nil? %>
    <strong>No route assigned<strong>
  <% else %>
    <strong>Route: </strong> 
    <%= link_to "#{@train.route.name}", route_path(@train.route) %>
  <% end %>
</p>

<p>
  <% if @train.current_station.nil? %>
    <strong>No current station assigned<strong>
  <% else %>
    <strong>Current_station: </strong> 
    <%= link_to "#{@train.current_station.title}", railway_station_path(@train.current_station)  %>
  <% end %>
</p>

<p>
  <% if @train.cars.empty? %>
    <strong>No cars<strong>
  <% else %>
    <strong>Cars:</strong> 
    <% @train.cars.each do |c| %>
      <%= link_to c.number, car_path(c) %>
    <% end %>  
  <% end %>
</p>

<p>
  <% 
    top = 0 
    lower = 0 
    @train.cars.each do |c| 
      top += c.top_places || 0
      lower += c.bottom_places || 0
    end 
  %> 

  <strong> Top places: </strong> <%= top %> <br>
  <strong> Lower places: </strong> <%= lower %>
</p>

<p>
  <%= link_to 'Add car', new_train_car_path(@train) %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>